---
- hosts: build
  become: true
  tasks:
    - name: Install Java and Maven
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - openjdk-8-jdk
        - maven

    - name: Clone the source code repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /opt/hello-world
        version: master

    - name: Build the project
      command: mvn package -f /opt/hello-world/pom.xml
