---
- hosts: build
  become: true
  tasks:
    - name: Install Java, Maven, Git
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - openjdk-8-jdk
        - maven
        - git

    - name: Clone the source code repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /opt/hello-world
        version: master

    - name: Build the project
      command: mvn package -f /opt/hello-world/pom.xml

- hosts: production
  become: true
  tasks:
    - name: Install Java and Tomcat
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - openjdk-8-jre
        - tomcat8

    - name: Deploy the app to Tomcat
      copy:
        src: /opt/hello-world/target/hello-1.0.war
        dest: /var/lib/tomcat8/webapps/hello.war
        mode: 0644

    - name: Restart Tomcat
      service:
        name: tomcat8
        state: restarted